[workspace]

members = [
    "crypto/tbs",
    "ln-gateway",
    "fedimint",
    "fedimint-core",
    "fedimint-derive",
    "fedimint-api",
    "client/cli",
    "client/client-lib",
    "modules/fedimint-mint",
    "modules/fedimint-ln",
    "modules/fedimint-wallet",
    "integrationtests",
]
resolver = "2"

[patch.crates-io]
bitcoin_hashes = { version = "0.10.0", git = 'https://github.com/fedimint/bitcoin_hashes', branch = 'fedimint' }
secp256k1-zkp = { git = "https://github.com/fedimint/rust-secp256k1-zkp/", branch = "sanket-pr" }
cln-plugin = { git = "https://github.com/ElementsProject/lightning", rev = "42783aa" }
cln-rpc = { git = "https://github.com/ElementsProject/lightning", rev = "42783aa" }
