[package]
name = "fedimint-derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[features]
diagnostics = []

[dependencies]
heck = "0.3"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
